#include <cat/err.h>
#include <stdio.h>
#include <stdlib.h>

/* Compile with -t -T TOK_ */


%%

grammar <- A BB* CCC !.

%%


static int nextc(void *p)
{
	int **vp = p;
	int tok = **vp ? **vp : -1;
	if ( tok > 0 ) *vp += 1;
	return tok;
}


void test_array(int *arr, const char *name, int erv)
{
	int rv;
	struct cpeg_parser parser;
	cpeg_init(&parser, &nextc);
	rv = cpeg_parse(&parser, &arr, NULL);
	cpeg_fini(&parser);
	printf("%s: %d %s\n", name, rv, (rv == erv) ? "PASSED" : "FAILED");
}


int main(int argc, char *argv[])
{
	int rv;
	int test1[] = { TOK_A, TOK_CCC, 0 };
	int test2[] = { TOK_A, TOK_BB, TOK_CCC, 0 };
	int test3[] = { TOK_A, TOK_BB, TOK_BB, TOK_BB, TOK_CCC, 0 };
	int test4[] = { TOK_A, 0 };
	int test5[] = { TOK_A, TOK_BB, TOK_CCC, TOK_BB, 0 };

	test_array(test1, "test1", 1);
	test_array(test2, "test2", 1);
	test_array(test3, "test3", 1);
	test_array(test4, "test4", -1);
	test_array(test5, "test5", -1);

	return 0;
}
